config/routes.rb
Rails.application.routes.draw do

  get '/calcula_tu_ahorro' => 'pages#calcula_tu_ahorro'
  get '/gestion_de_flotas' => 'pages#gestion_de_flotas'
  get '/taller_de_diesel' => 'pages#taller_de_diesel'
  get '/portal_clientes' => 'pages#portal_clientes'

  resources :contacts, only: [:new, :create]

  root 'welcome#index'

  
end

app/models/contact.rb
class Contact < MailForm::Base

	attribute :name, 					:validate => true
	attribute :email, 				:validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message, 			:validate => true
	attribute :gas,						:validate => true
	attribute :mant,					:validate => true
	attribute :nickname, 			:captcha => true

def headers 
	{
	:subject => "Contact form",
	:to => "alejandroromo14@gmail.com",
	:from => %("#{name}" <#{email}>)
	}
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:notice] = 'No se puede enviar el mensaje en este momento.'
      render :new
    end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def calcula_tu_ahorro

    @q = params[:quantity]
    @r = params[:quantity2]
    @p = 0.5
  end

  def gestion_de_flotas
    @contact = Contact.new
  end

  def taller_de_diesel
    @contact = Contact.new
  end

  def portal_clientes
  end

  def contacto
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<div id="banner" class="cover_contact">
	<h1>Contáctanos Ahora</h1>
</div>


<div class="wraper">
<h1>Gracias por comunicarte con nosotros</h1>
<p>En seguida nos ponemos en contacto contigo</p>

</div>

app/views/contacts/new.html.erb
<div id="banner" class="cover_contact">
	<h1>Contáctanos Ahora </h1>
</div>

<div class="container">
<div class="row">
<div id="texto" class="col-md-8 col-md-offset-2">
	<p>Si tienes alguna duda o comentario en particular no dudes en escribirnos. Uno de nuestros consultores se comunicará contigo en las próximas 48 horas
</p>
</div>
</div>
</div>


	<div class="container">
	<div class="col-md-6 col-md-offset-3" id="form">
	<%= form_for @contact do |f| %>
		<%= f.label :nombre %><br>
		<%= f.text_field :name, required: true %>

		<br>


		<%= f.label :email %><br>
		<%= f.email_field :email, required: true %>

		<br>

		<%= f.label :mensaje %><br>
		<%= f.text_area :message, as: :text, class:"contacto_area" %>

		<div class="hidden">
			<%= f.label :nickname %><br>
			<%= f.text_field :nickname, hint: 'Esto se queda en blanco' %>
		</div>

<br>
<br>
		<%= f.submit 'Enviar mensaje', class: "button button_red button_block" %>
	<% end %>
	</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Planher</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to(image_tag("logo.png"), root_path, class: "navbar-brand logo2") %>
      
      <%= link_to "Planher", root_path, id: "logo", class: "navbar-brand logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse nav" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
              <li><%= link_to "Gestión de Flotas", gestion_de_flotas_path, id: "ojo" %></li>
              <li><%= link_to "Taller de Diesel", taller_de_diesel_path, id: "ojo" %></li>
              <li><%= link_to "Calcula tu ahorro", calcula_tu_ahorro_path, id: "ojo" %></li>
              <li><%= link_to "Portal de Clientes", portal_clientes_path, id: "ojo" %></li>
              <li><%= link_to "Contacto", new_contact_path, id: "ojo" %></li>
          </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

<%= yield %>

    <footer class="footer-basic-centered">

      <p class="footer-company-motto">Planher: Optimizando operaciones</p>

      <p class="footer-links">
        <a href="#"><span class="fa fa-building-o" aria-hiden="true"></span>Oficina: 6608-8219</a>
        ·
        <a href="5545177442"><span class="fa fa-mobile" aria-hiden="true"></span>Celular: 55 4517-7442</a>
        ·
        <a href="5545177442"><span class="fa fa-whatsapp" aria-hiden="true"></span>Whatsapp: 55 4517-7442</a>
        ·
        <a href="mailto:contacto@planher.mx?Subject=Solicitud%20de%20información"><span class="fa fa-envelope-o" aria-hiden="true"></span>contacto@planher.mx</a>
        · 
        <%= link_to "Agenda una cita y uno de nuestros consultores irá con gusto", new_contact_path %>
        
      </p>

      <p class="footer-company-name">Planher &copy; 2016</p>

    </footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>

app/views/pages/calcula_tu_ahorro.html.erb
<div id="banner" class="cover_ahorro">
	<h1>Cálcula tu Ahorro </h1>
	<h3>LO QUE NO SE MIDE, NO SE CONTROLA. LO QUE NO SE CONTROLA, NO SE MEJORA</h3>
</div>

<div class="container">
<div class="row">
<div id="texto" class="col-md-8 col-md-offset-2">
	<p>¿Tienes idea del ahorro que podrías tener en la gestión de tu flotilla si cuidaras a tus unidades y cómo se desempeñan? Estamos convencidos de que lo que no se mide no se controla, y lo que no se controla no se mejora. Te enseñamos, con esta herramienta, el ahorro que podrías tener si gestionaras tu flotilla con nuestro sistema</p>
</div>
</div>
</div>


<!-- cotizador  -->
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3" id="cotiza">
<div class="titulos">
	<h1><strong>Calcula tu ahorro</strong></h1>
</div>
			<form>
				<label>¿Sabes cuál es el gasto mensual en Diesel? (MXN)</label> <br>
				<input type="number" id="gas" name="quantity"> <br>
				<label>¿Sabes cuál es el gasto de mantenimiento correctivo mensual? (MXN) </label> <br>
				<input type="number" id="man" name="quantity2"> <br><br><br>
				<button class="button button_red button_block" id="15">Quiero calcular mi ahorro</button>

			</form>
		</div>
	</div>
</div>


<div class="container"><div class="contar">
	<h1> Tu ahorro con nosotros es de <strong>
	 <%=
	 	x = (@q.to_f + @r.to_f)*12 

	 	x = x* 0.05

	 	x.round

	 	
	 	
	 %> </strong> anual </h1>
</div>
</div>

<div class="container"><div class="contar">
	<h1> Tu ahorro con nosotros es de <strong>
	 <%=
	 	x = (@q.to_f + @r.to_f)*36 

	 	x = x* 0.05

	 	x.round

	 	
	 	
	 %></strong>  al finalizar la metodología </h1>
</div>
</div>

<div class="container">
<div class="col-md-6 caja">
	<%= image_tag src="gear.jpg", :class =>"fot" %>
</div>



	<div class="col-md-6">
	<h3 class="tit"><strong>TE LO DEMOSTRAMOS</strong></h3>
	<p class="just">¿Te preguntas cómo es que una mejor gestión de las flotillas pueda ayudar a tu empresa? ¡Te invitamos a utilizar nuestro calculador de ahorro! Con él te mostraremos el ahorro aproximado que podrás tener al utilizar nuestro sistema aplicado a tu flotilla.</p>
	</div>
</div>

app/views/pages/contacto.html.erb
<div id="banner" class="cover_home">
	<h1>Contáctanos Ahora </h1>
	<h3>Ahorra. Diseña. Aprende</h3>
</div>




<div class="wraper_super_skiny">
<div id="nume">

<ul>
	<li>
		<h5>31</h5>
		<hr>
		<h6>kms recorridos</h6>
	</li>

		<li>
		<h5>150</h5>
		<hr>
		<h6>litros ahorrados</h6>
	</li>

		<li>
		<h5>$200,000</h5>
		<hr>
		<h6>pesos ahorrados</h6>
	</li>

</ul>

</div>
</div>

app/views/pages/gestion_de_flotas.html.erb
<div id="banner" class="cover_gestion">
	<h1>Gestión de Flotas</h1>
</div>

<section>
	<div class="wraper_super_wide">
	<div id="servicios">
		<div class="servicio">
			<span class="fa fa-file-text-o" aria-hidden="true"></span>
			<h3>Diagnóstico</h3>
			<p>Analizamos la situación actual de tu flota y definimos entregables y estrategia a seguir. </p>
		</div>

				<div class="servicio">
				<span class="fa fa-pencil-square-o" aria-hidden="true"></span>
			<h3>Diseño</h3>
			<p>Mapeamos y planeamos las acciones a la medida para optimizar el beneficio de tu flota</p>
		</div>

				<div class="servicio">
				<span class="fa fa-cogs" aria-hidden="true"></span>
			<h3>Capacitación</h3>
			<p>Nos aseguramos que a todo tu personal le quede absolutamente claro el por qué del proyecto y el cómo lo vamos a conseguir.</p>
		</div>

				<div class="servicio">
				<span class="fa fa-briefcase" aria-hidden="true"></span>
			<h3>Implementación</h3>
			<p>Ejecutamos las acciones diseñadas hombro a hombro con tu personal hasta lograr un beneficio demostrable económicamente</p>
		</div>

				<div class="servicio">
				<span class="fa fa-hand-o-right" aria-hidden="true"></span>
			<h3>Seguimiento</h3>
			<p>Auditorias continuas para garantizar  que todo el proyecto siga generando beneficios.
</p>
		</div>


	</div>
</section>

<!--  -->

<div class="margen"></div>

<div class="container">
<div class="col-md-6">
	<%= image_tag src="control.jpg", :class =>"fot" %>
</div>

	<div class="col-md-6">
	<h3 class="tit"><strong>LA CLAVE ESTÁ EN EL SISTEMA</strong></h3>
	<p class="just">Estamos tan seguros de que el sistema funciona que te lo garantizamos por escrito. Pero claro, como todo, la teoría por sí sola no funciona, te ayudamos a que la ejecución de cada paso sea la adecuada a tus circunstancias particulares para lograr el mayor impacto posible</p>
	</div>
</div>
	
<div class="container">
<div class="col-md-6 col-md-offset-3">
<div id="form">
<div class="row">

	<%= form_for @contact do |f| %>
		<%= f.label :nombre %><br>
		<%= f.text_field :name, required: true %>

		<br>

		<%= f.label :email %><br>
		<%= f.email_field :email, required: true %>

		<br>

		<%= f.label :mensaje %><br>
		<%= f.text_area :message, as: :text, class:"contacto_area" %>

		<div class="hidden">
			<%= f.label :nickname %><br>
			<%= f.text_field :nickname, hint: 'Esto se queda en blanco' %>
		</div>

<br>
<br>
		<%= f.submit 'Enviar mensaje', class: "button button_red button_block" %>
	<% end %>

</div>	
</div>
</div>
</div>

app/views/pages/portal_clientes.html.erb
<div id="banner" class="cover_clientes">
	<h1>Nuestros consentidos</h1>
</div>


<div class="container">
<div class="row">
<div id="texto" class="col-md-8 col-md-offset-2">
	<p>Para nosotros, tú y tu flotilla son lo más importante. Por eso te damos un espacio personalizado a través del cual podrás registrar el rendimiento de tus unidades para gestionarlas de la mejor manera.</p>
</div>
</div>
</div>


<!-- cotizador  -->
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3" id="cotiza">
<div class="titulos">
	<h1><strong>Ingresa Ahora</strong></h1>
</div>
			<form>
				<label>Nombre de Usuario</label> <br>
				<input type="email" name="cliente"> <br>
				<label>Contraseña</label> <br>
				<input type="password" name="password"> <br>
				<div class="button button_red button_block bloque">Ingresar</div>

			</form>
		</div>
	</div>
</div>

app/views/pages/taller_de_diesel.html.erb
<div id="banner" class="cover_taller">
	<h1>Taller de Diesel</h1>
</div>

<div class="container">
<div class="row">
<div id="texto" class="col-md-8 col-md-offset-2">
	<p>Con nuestro servicio mecánico, nuestros clientes tienen la seguridad y garantía que están trabajando con ingenieros profesionales en Diésel. Además de contar con el respaldo de un servicio que estará disponible las 24 horas los 365 días del año, en caso de cualquier eventualidad</p>
</div>
</div>
</div>

<br>


<div class="container">
<div class="titulos">
	<h1>Nuestra oferta de valor</h1>
</div>
</div>

<section>
	<div class="wraper_super_wide">
	<div id="servicios2">
		
		<div class="row">
		<div class="servicio2">
			<span class="fa fa-shield" aria-hidden="true"></span>
			<p>Técnicos expertos, especializados en motores diésel, y sistemas de unidades de carga</p>
		</div>

				<div class="servicio2">
			<span class="fa fa-spinner" aria-hidden="true"></span>
			<p>Mantenimiento preventivo y correctivo</p>
		</div>

				<div class="servicio2">
			<span class="fa fa-first-order" aria-hidden="true"></span>
			<p>Escaneo de unidades cualquier marca</p>
		</div>

				<div class="servicio2">
			<span class="fa fa-cog" aria-hidden="true"></span>
			<p>Equipo de técnicos móvil: para acudir a realizar servicios donde lo requiera el cliente</p>
		</div>
	</div>

	<div class="row">
				<div class="servicio2">
			<span class="fa fa-road" aria-hidden="true"></span>
			<p>Auxilio en camino (contamos con una flota de gruas)</p>
		</div>

						<div class="servicio2">
			<span class="fa fa-file-text" aria-hidden="true"></span>
			<p>Diagnóstico e información de reparaciones documentada</p>
		</div>

						<div class="servicio2">
			<span class="fa fa-archive" aria-hidden="true"></span>
			<p>Entrega de refacciones remplazadas</p>
		</div>

						<div class="servicio2">
			<span class="fa fa-certificate" aria-hidden="true"></span>
			<p>Garantía de servicio firmada y por escrito. </p>
		</div>
	</div>
	</div>
</section>

<!--  -->


<div class="container">
<div class="col-md-6">
	<%= image_tag src="lock.jpg", :class =>"fot" %>
</div>

	<div class="col-md-6">
	<h3 class="tit"><strong>EL DE MÁS CONFIANZA</strong></h3>
	<p class="just">Sabemos lo difícil que es encontrar un taller de confianza en el que no te vean la cara en el diagnóstico y te cobren lo que en verdad trabajaron. Te ofrecemos uno de los mejores talleres de motores diesel para que tu flotilla siempre esté “a punto”</p>
	</div>
</div>



	<div class="container">
	<div class="col-md-6 col-md-offset-3" id="form">
	<%= form_for @contact do |f| %>
		<%= f.label :nombre %><br>
		<%= f.text_field :name, required: true %>

		<br>

		<%= f.label :email %><br>
		<%= f.email_field :email, required: true %>

		<br>

		<%= f.label :mensaje %><br>
		<%= f.text_area :message, as: :text, class:"contacto_area" %>

		<div class="hidden">
			<%= f.label :nickname %><br>
			<%= f.text_field :nickname, hint: 'Esto se queda en blanco' %>
		</div>

<br>
<br>
		<%= f.submit 'Enviar mensaje', class: "button button_red button_block" %>
	<% end %>
	</div>
	</div>

app/views/welcome/index.html.erb
<div id="banner" class="cover_home">
	<h1>Mejora el rendimiento de tus camiones diesel </h1>
	<h3>Optimizando Operaciones</h3>
</div>



<div class="wraper_wide">
<div id="tres">
	<ul>
		<%= link_to gestion_de_flotas_path do %>
		<li>
			<%= image_tag src="gestion2.jpg" %>
			<h3>Gestión de Flotas</h3>
		</li>
		<% end %>
<!--  -->
		<%= link_to taller_de_diesel_path do %>
		<li>
			<%= image_tag src="taller2.jpg" %>
			<h3>Taller de Diesel</h3>	
		</li>
		<% end %>
<!--  -->

	<!--  -->
		<%= link_to calcula_tu_ahorro_path do %>
		<li>
			<%= image_tag src="ahorro2.jpg" %>	
			<h3>Calcula tu ahorro</h3>		
		</li>
		<% end %>
<!--  -->
	</ul>
</div>
</div>

<div class="container">
<div class="row">
<div id="texto" class="col-md-8 col-md-offset-2">
	<p>Entendemos perfectamente lo complejo que puede ser gestionar una flotilla, independientemente del objetivo que ella tenga. No solamente se trata de tener las unidades en las mejores condiciones para que siempre ofrezcan el máximo rendimiento, sino cumplir en tiempo y forma con los compromisos que tengas</p>
</div>
</div>
</div>

<div class="container">
<div class="col-md-6">
	<%= image_tag src="control.jpg", :class =>"fot" %>
</div>

	<div class="col-md-6">
	<h3 class="tit"><strong>LO QUE NO SE MIDE, NO SE CONTROLA. LO QUE NO SE CONTROLA, NO SE MEJORA</strong></h3>
	<p class="just">Comienza a medir el rendimiento de tu flotilla de camiones diesel para conocer qué tan bien o mal son utilizados. Controla el rendimiento a través de nuestro sistema de gestión de flotillas para ir mejorando, poco a poco, paso a paso</p>
	</div>
</div>

<div class="row">
<div id="texto" class="col-md-8 col-md-offset-2">
	<p></p>
</div>
</div>


<div class="container">
<div class="col-md-6">
		<h3 class="tit"><strong>NADIE COMO NOSOTROS</strong></h3>
	<p class="just">Hemos desarrollado, gracias a nuestra experiencia en el manejo de flotillas, una metodología propia que te enseñaremos para que la gestión de tus camiones deje de ser un peso y comience a ser una de las mejores partes de tu empresa</p>
	
</div>

	<div class="col-md-6">
		<%= image_tag src="fleet.jpg", :class =>"fot" %>
	</div>
</div>